# This is a basic workflow to help you get started with Actions

name: DeployTerraform

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: azuretf
          path: ${{ github.workspace }}//azuretf
      
  deploy-dev-infra:
    name: Deploy Infra Dev
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}//azuretf

    environment:
      name: dev

    needs: build
    steps:
      - name: Download Terraform
        uses: actions/download-artifct@v2
        with: 
          name: azuretf
          path: ${{ github.workspace }}//azuretf

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init
    
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Workspace
        id: workspace
        run: terraform workspace select dev
  
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true